# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkssl < Formula
  desc "Simple tool to check or monitor TLS/SSL certificates are working."
  homepage "https://www.checkssl.org/"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/szazeski/checkssl/releases/download/v1.0.0/checkssl_Darwin_x86_64.tar.gz"
      sha256 "15521f8de80753b6f965584bd64191146c12343ed6191d5fa3cb289d8f706331"

      def install
        bin.install "checkssl"
      end
    end
    on_arm do
      url "https://github.com/szazeski/checkssl/releases/download/v1.0.0/checkssl_Darwin_arm64.tar.gz"
      sha256 "3820c83fc79fc2755ae09db0eb1f437cc2c7b25dc4c139d2a94635f4756c0941"

      def install
        bin.install "checkssl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szazeski/checkssl/releases/download/v1.0.0/checkssl_Linux_x86_64.tar.gz"
        sha256 "bab27d00fcda0044d85e9a6fef1875b43afa511e16338211ddceb248276d22f9"

        def install
          bin.install "checkssl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/szazeski/checkssl/releases/download/v1.0.0/checkssl_Linux_arm64.tar.gz"
        sha256 "d59801e4ac3bf5bc3d184d92a8410644033f0e958389d96505d9b5f01c5ac330"

        def install
          bin.install "checkssl"
        end
      end
    end
  end

  test do
    system "#{bin}/checkssl checkssl.org"
  end
end
