# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp3edit < Formula
  desc "Simple cli to view or change mp3 id3 tags."
  homepage "https://opensource.zazeski.com/"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szazeski/mp3edit/releases/download/v1.0.4/mp3edit_Darwin_arm64.tar.gz"
      sha256 "18715db825a94b6df06b1ba334b78c0641a509a54ec03df9fc10a854bfdf51f9"

      def install
        bin.install "mp3edit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/mp3edit/releases/download/v1.0.4/mp3edit_Darwin_x86_64.tar.gz"
      sha256 "2cd9265844589e44fa14de2aaf8a997f2bafb1a15c68479b8e934d3b60d6df80"

      def install
        bin.install "mp3edit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/szazeski/mp3edit/releases/download/v1.0.4/mp3edit_Linux_x86_64.tar.gz"
      sha256 "61b40179f5f88582a04f446aff23e909441fc0f17dc63da05292e450a95a3a26"

      def install
        bin.install "mp3edit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szazeski/mp3edit/releases/download/v1.0.4/mp3edit_Linux_arm64.tar.gz"
      sha256 "fac1139a183bd12634bdd85676021fd310f1fa5822753cb59e37a7ff2febf7d7"

      def install
        bin.install "mp3edit"
      end
    end
  end

  test do
    system "#{bin}/mp3edit -version"
  end
end
